version: '3.7'

services:
  webserver:
    build:
      context: ./application/webserver
      dockerfile: development.dockerfile
    ports:
    - 8888:80

  backend:
    build:
      context: ./application/backend
      dockerfile: development.dockerfile
    ports:
      - 8800:8000
    volumes:
      - ./application/backend:/usr/src/app

  frontend:
    tty:
      true
    build:
      context: ./application/frontend
      dockerfile: development.dockerfile
    ports:
      - 8000:5000
    volumes:
      - type: bind
        source: ./application/frontend
        target: /app
        # This is for Windows - when the container accesses a file, it gets the latest version. 
        consistency: delegated
      - node_modules:/app/node_modules
      # expanded notation looks like this:
      #- type: volume
      #  source: node_modules
      #  target: /app/node_modules


volumes:
  node_modules:
